name: workflow-call 
on:
  push:
    # branches:
    #   - 'main'

jobs:
  feature-pipeline:
    if: github.ref_name != 'main'
    uses: aikdp/workflows/.github/workflows/nodejs-eks-feature_2.yaml@main # Path of the  repository
    with:
      project: 'roboshop'
      component: 'catalogue' 


  main-workflow:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: main workflow 
        run: echo "This will executed when commit comes to mian branch"