name: context
on: 
  push:
env:
  project: "roboshop"
  component: "catalogue"
  environment: dev
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: sprint env variables
        run: |
          echo "Project is: $project"
          echo "Environment is: $environment"
      
      - name: print GitHub context
        env:
          GITHUB_CONETXT: ${{  toJson(github) }}
        run: echo "$GITHUB_CONETXT"

      - name: Add variables to env
        run:  |
          echo "course=github-actions" >> $GITHUB_ENV
          echo "duration=10Hours" >> $GITHUB_ENV

      - name: Access another step variables
        run: |
          echo "Course is: $course"
          echo "I am able access the another step vars in this setp, the duration is: $duration"