name: context
on: 
  push:
env:
  project: "roboshop"
  component: "catalogue"
  environment: dev
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: sprint env variables
        run: |
          echo "Project is: $project"
          echo "Environment is: $environment"
      
      - name: print GitHub context
        env:
          GITHUB_CONETXT: ${{  toJson(github) }}
        run: echo "$GITHUB_CONETXT"