name: conditions
on: 
  push:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch 
        if: github.ref_name == 'main'
        run: echo "This will execute when main branch updated"

      - name: Check branch 
        if: github.ref_name !== 'main'
        run: echo "This will execute when Feature branch updated"